spring.application.name=creator
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:h2:mem:hcreatordb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

admin.init.username=${ADMIN_INIT_USERNAME:admin}
admin.init.password=${ADMIN_INIT_PASSWORD:changeme1234}

aws.s3.bucket=hcreator-files
aws.s3.region=ap-northeast-2
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}