spring.application.name=creator
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/hcreatordb?sslMode=trust
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

admin.init.username=${ADMIN_INIT_USERNAME:admin}
admin.init.password=${ADMIN_INIT_PASSWORD:changeme1234}

aws.s3.bucket=hcreator-files
aws.s3.region=ap-northeast-2
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.cloudfront.domain=d3vk83zpkldt5i.cloudfront.net